### ISSUE TITLE
Why was the upstream deleted

### ISSUE THREAD

**Issue by tryoxiss** [tryoxiss/atkinson-hyperlegible-pro#2]
@jacobxperez I noticed you deleted the upstream repository (jacobxperez/atkinson-hyperlegible-pro), is there a reason for it? If so, why would you delete it instead of archiving it?

**Comment by jacobxperez** [comment]
Sorry, I could not obtain permission to continue using the name "Atkinson Hyperlegible" from the Braille Institute. I was however permitted to continue the project under a different name, I just haven't had time to change everything to the new name. The project was set as a private repository for now and everything still exists and is intact. I will try to publish as soon as I can. Thanks for reaching out.

**Comment by jacobxperez** [comment]
@tryoxiss Sorry, I could not obtain permission to continue using the name "Atkinson Hyperlegible" from the Braille Institute. I was however permitted to continue the project under a different name, I just haven't had time to change everything to the new name. The project was set as a private repository for now and everything still exists and is intact. I will try to publish as soon as I can. Thanks for reaching out.

**Comment by tryoxiss** [comment]
> @tryoxiss Sorry, I could not obtain permission to continue using the name "Atkinson Hyperlegible" from the Braille Institute. I was however permitted to continue the project under a different name, I just haven't had time to change everything to the new name. The project was set as a private repository for now and everything still exists and is intact. I will try to publish as soon as I can. Thanks for reaching out.

No worries, I was just a bit anxious when I saw one of my favorite projects fall of the face of the earth :sweat:. The name thing sucks but makes sense. You should probably update this thread (and ill update the README) when the new repo is up, as github seems to have crowned this the new upstream because of making it private.

**Comment by jacobxperez** [comment]
@tryoxiss I will soon be releaseing Atkinson Hyperlegible Pro under its new name Lexica Ultralegible. This name change reflects our commitment to enhancing readability and accessibility for all users, particularly those with low vision. "Lexica" emphasizes the linguistic aspect of the font, reinforcing its purpose as a tool for clear communication. "Ultralegible" highlights our dedication to superior legibility, ensuring that text is easy to read in various contexts.

**Comment by jacobxperez** [comment]
@tryoxiss We are excited to announce a new direction for our font project, formerly "Atkinson Hyperlegible Pro". To comply with the Open Font License (OFL) and respect the original creator’s rights, we have rebranded our typeface as **[Lexica Ultralegible](https://github.com/jacobxperez/lexica-ultralegible)**.

**Comment by tryoxiss** [comment]
> @tryoxiss We are excited to announce a new direction for our font project, formerly "Atkinson Hyperlegible Pro". To comply with the Open Font License (OFL) and respect the original creator’s rights, we have rebranded our typeface as **[Lexica Ultralegible](https://github.com/jacobxperez/lexica-ultralegible)**.

Thanks for the update! I'll update the readme to direct people to the new repo. Glad to see this project back in the light.

**Comment by tryoxiss** [comment]
Thats done now :3
